### PR TITLE
Added English translation

### PR DESCRIPTION
**Pull request by hophacker**

### CODE REVIEW

**Comment by canius** [comment]
那你pull request标题应该用英语。。

**Comment by xinhuang327** [comment]
Nicely done! This is the translated version of original Chinese Readme.

**Comment by UltimatePea** [comment]
Great work! but would you please use Non-Inflammatory Articulations

**Comment by hophacker** [comment]
@UltimatePea Well, that's the direct translation of the original Chinese, and the original one is a little bit inflammatory too...

**Comment by hophacker** [comment]
@canius Thanks

**Pull request closed without merging**
